        INTEGER PGSGCT_E_NO_DATA_FILES
        PARAMETER (PGSGCT_E_NO_DATA_FILES = 101888)
        INTEGER PGSGCT_E_GCTP_ERROR
        PARAMETER (PGSGCT_E_GCTP_ERROR = 101889)
        INTEGER PGSGCT_E_BAD_INC_ANGLE
        PARAMETER (PGSGCT_E_BAD_INC_ANGLE = 101890)
        INTEGER PGSGCT_E_BAD_RADIUS
        PARAMETER (PGSGCT_E_BAD_RADIUS = 101891)
        INTEGER PGSGCT_E_BAD_MINOR_AXIS
        PARAMETER (PGSGCT_E_BAD_MINOR_AXIS = 101892)
        INTEGER PGSGCT_E_MINOR_GT_MAJOR
        PARAMETER (PGSGCT_E_MINOR_GT_MAJOR = 101893)
        INTEGER PGSGCT_E_BAD_LONGITUDE
        PARAMETER (PGSGCT_E_BAD_LONGITUDE = 101894)
        INTEGER PGSGCT_E_BAD_LATITUDE
        PARAMETER (PGSGCT_E_BAD_LATITUDE = 101895)
        INTEGER PGSGCT_E_INVD_SPCS_SPHEROID
        PARAMETER (PGSGCT_E_INVD_SPCS_SPHEROID = 101896)
        INTEGER PGSGCT_E_BAD_ZONE
        PARAMETER (PGSGCT_E_BAD_ZONE = 101897)
        INTEGER PGSGCT_E_BAD_DIRECTION
        PARAMETER (PGSGCT_E_BAD_DIRECTION = 101898)
        INTEGER PGSGCT_E_INVD_PROJECTION
        PARAMETER (PGSGCT_E_INVD_PROJECTION = 101899)
        INTEGER PGSGCT_E_NO_POINTS
        PARAMETER (PGSGCT_E_NO_POINTS = 101900)
        INTEGER PGSGCT_W_INTP_REGION
        PARAMETER (PGSGCT_W_INTP_REGION = 101389)
        INTEGER PGSGCT_E_STD_PARALLEL
        PARAMETER (PGSGCT_E_STD_PARALLEL = 101902)
        INTEGER PGSGCT_E_ITER_EXCEEDED
        PARAMETER (PGSGCT_E_ITER_EXCEEDED = 101903)
        INTEGER PGSGCT_E_POINT_PROJECT
        PARAMETER (PGSGCT_E_POINT_PROJECT = 101904)
        INTEGER PGSGCT_E_INPUT_DATA_ERROR
        PARAMETER (PGSGCT_E_INPUT_DATA_ERROR = 101905)
        INTEGER PGSGCT_E_STD_PARALLEL_OPP
        PARAMETER (PGSGCT_E_STD_PARALLEL_OPP = 101906)
        INTEGER PGSGCT_E_INFINITE
        PARAMETER (PGSGCT_E_INFINITE = 101907)
        INTEGER PGSGCT_E_ITER_FAILED
        PARAMETER (PGSGCT_E_ITER_FAILED = 101908)
        INTEGER PGSGCT_E_PROJECT_FAILED
        PARAMETER (PGSGCT_E_PROJECT_FAILED = 101909)
        INTEGER PGSGCT_E_POINTS_ON_POLES
        PARAMETER (PGSGCT_E_POINTS_ON_POLES = 101910)
        INTEGER PGSGCT_E_ITER_SOM
        PARAMETER (PGSGCT_E_ITER_SOM = 101911)
        INTEGER PGSGCT_E_SPCS_ZONE
        PARAMETER (PGSGCT_E_SPCS_ZONE = 101912)
        INTEGER PGSGCT_E_SPCS_FILE
        PARAMETER (PGSGCT_E_SPCS_FILE = 101913)
        INTEGER PGSGCT_E_CONV_ERROR
        PARAMETER (PGSGCT_E_CONV_ERROR = 101914)
        INTEGER PGSGCT_E_LAT_15
        PARAMETER (PGSGCT_E_LAT_15 = 101915)
        INTEGER PGSGCT_E_LAT_CONVERGE
        PARAMETER (PGSGCT_E_LAT_CONVERGE = 101916)
        INTEGER PGSGCT_E_ISIN_ERROR
        PARAMETER (PGSGCT_E_ISIN_ERROR = 101917)
        INTEGER PGSGCT_E_DMS_ERROR
        PARAMETER (PGSGCT_E_DMS_ERROR = 101918)
        INTEGER PGSGCT_E_INVERSE_FAILED
        PARAMETER (PGSGCT_E_INVERSE_FAILED = 101919)
        INTEGER PGSGCT_E_NO_RMAJORRMINOR
        PARAMETER (PGSGCT_E_NO_RMAJORRMINOR = 101920)
        INTEGER PGSGCT_E_INVALID_SWITCH
        PARAMETER (PGSGCT_E_INVALID_SWITCH = 101921)
