        INTEGER PGSAA_S_NEWFILE
        PARAMETER (PGSAA_S_NEWFILE = 82432)
        INTEGER PGSAA_E_SUPPORTFILE
        PARAMETER (PGSAA_E_SUPPORTFILE = 85505)
        INTEGER PGSAA_E_CHECK_CALL
        PARAMETER (PGSAA_E_CHECK_CALL = 85506)
        INTEGER PGSAA_E_PARMSNOTFOUND
        PARAMETER (PGSAA_E_PARMSNOTFOUND = 85507)
        INTEGER PGSAA_E_DATARATEUNSET
        PARAMETER (PGSAA_E_DATARATEUNSET = 85508)
        INTEGER PGSAA_E_PARMSFROMANYFILES
        PARAMETER (PGSAA_E_PARMSFROMANYFILES = 85509)
        INTEGER PGSAA_E_INVALIDNOPARMS
        PARAMETER (PGSAA_E_INVALIDNOPARMS = 85510)
        INTEGER PGSAA_E_BADSUPPSUPPORT
        PARAMETER (PGSAA_E_BADSUPPSUPPORT = 85511)
        INTEGER PGSAA_E_CANTFINDFILE
        PARAMETER (PGSAA_E_CANTFINDFILE = 85512)
        INTEGER PGSAA_E_FFERROR
        PARAMETER (PGSAA_E_FFERROR = 85513)
        INTEGER PGSAA_E_FFDBIN
        PARAMETER (PGSAA_E_FFDBIN = 85514)
        INTEGER PGSAA_E_FFDBSET
        PARAMETER (PGSAA_E_FFDBSET = 85515)
        INTEGER PGSAA_E_FFDBEVENTS
        PARAMETER (PGSAA_E_FFDBEVENTS = 85516)
        INTEGER PGSAA_E_MALLOC
        PARAMETER (PGSAA_E_MALLOC = 85517)
        INTEGER PGSAA_E_CANT_PARSE_FILE
        PARAMETER (PGSAA_E_CANT_PARSE_FILE = 85518)
        INTEGER PGSAA_E_PEV_ERROR
        PARAMETER (PGSAA_E_PEV_ERROR = 85519)
        INTEGER PGSAA_E_PEV_XS_SUPPFILES
        PARAMETER (PGSAA_E_PEV_XS_SUPPFILES = 85520)
        INTEGER PGSAA_E_CANT_GET_VALUE
        PARAMETER (PGSAA_E_CANT_GET_VALUE = 85521)
        INTEGER PGSAA_E_CANT_GET_FILE
        PARAMETER (PGSAA_E_CANT_GET_FILE = 85522)
        INTEGER PGSAA_E_GETDBIN
        PARAMETER (PGSAA_E_GETDBIN = 85523)
        INTEGER PGSAA_E_CANT_GET_FILE_ID
        PARAMETER (PGSAA_E_CANT_GET_FILE_ID = 85524)
        INTEGER PGSAA_E_CANT_OPEN_INPUT_FILE
        PARAMETER (PGSAA_E_CANT_OPEN_INPUT_FILE = 85525)
        INTEGER PGSAA_E_AGG_CANT_BE_INSERTED
        PARAMETER (PGSAA_E_AGG_CANT_BE_INSERTED = 85526)
        INTEGER PGSAA_E_READLABEL_PARSE_ERROR
        PARAMETER (PGSAA_E_READLABEL_PARSE_ERROR = 85527)
        INTEGER PGSAA_E_PARAMETER_INVALID
        PARAMETER (PGSAA_E_PARAMETER_INVALID = 85528)
        INTEGER PGSAA_E_FIRST_NODE_NOT_FOUND
        PARAMETER (PGSAA_E_FIRST_NODE_NOT_FOUND = 85529)
        INTEGER PGSAA_E_PEVA_ERROR
        PARAMETER (PGSAA_E_PEVA_ERROR = 85530)
        INTEGER PGSAA_E_GETSUPP
        PARAMETER (PGSAA_E_GETSUPP = 85531)
        INTEGER PGSAA_E_POSITION_CALC_FAILURE
        PARAMETER (PGSAA_E_POSITION_CALC_FAILURE = 85532)
        INTEGER PGSAA_E_TWOD_READ_ERROR
        PARAMETER (PGSAA_E_TWOD_READ_ERROR = 85533)
        INTEGER PGSAA_E_EXTRACTORESULTSERROR
        PARAMETER (PGSAA_E_EXTRACTORESULTSERROR = 85534)
        INTEGER PGSAA_E_THREED_READ_ERROR
        PARAMETER (PGSAA_E_THREED_READ_ERROR = 85535)
        INTEGER PGSAA_E_OUTOFRANGE
        PARAMETER (PGSAA_E_OUTOFRANGE = 85536)
        INTEGER PGSAA_E_NPOINTSINVALID
        PARAMETER (PGSAA_E_NPOINTSINVALID = 85537)
        INTEGER PGSAA_E_GEOERROR
        PARAMETER (PGSAA_E_GEOERROR = 85538)
        INTEGER PGSAA_E_AUTOOPERATION
        PARAMETER (PGSAA_E_AUTOOPERATION = 85539)
        INTEGER PGSAA_E_AUTOOPERATIONUNSET
        PARAMETER (PGSAA_E_AUTOOPERATIONUNSET = 85540)
        INTEGER PGSAA_E_OPERATION
        PARAMETER (PGSAA_E_OPERATION = 85541)
        INTEGER PGSAA_E_OPERATIONUNSET
        PARAMETER (PGSAA_E_OPERATIONUNSET = 85542)
        INTEGER PGSAA_E_GEOTOSTRUCT
        PARAMETER (PGSAA_E_GEOTOSTRUCT = 85543)
        INTEGER PGSAA_E_DCW_ERROR
        PARAMETER (PGSAA_E_DCW_ERROR = 85544)
        INTEGER PGSAA_W_DCW_NODATA
        PARAMETER (PGSAA_W_DCW_NODATA = 85033)
        INTEGER PGSAA_E_CANT_FIND_PARM
        PARAMETER (PGSAA_E_CANT_FIND_PARM = 85546)
        INTEGER PGSAA_E_CANT_GET_POINT_INFO
        PARAMETER (PGSAA_E_CANT_GET_POINT_INFO = 85547)
        INTEGER PGSAA_E_CANT_GET_DATABASE_PATH
        PARAMETER (PGSAA_E_CANT_GET_DATABASE_PATH = 85548)
        INTEGER PGSAA_E_CANT_GET_AFT_PATH
        PARAMETER (PGSAA_E_CANT_GET_AFT_PATH = 85549)
        INTEGER PGSAA_E_NPARMSINVALID
        PARAMETER (PGSAA_E_NPARMSINVALID = 85550)
        INTEGER PGSAA_E_CANT_FIND_FACE
        PARAMETER (PGSAA_E_CANT_FIND_FACE = 85551)
        INTEGER PGSAA_E_TILE_STATUS
        PARAMETER (PGSAA_E_TILE_STATUS = 85552)
        INTEGER PGSAA_E_2DGEO
        PARAMETER (PGSAA_E_2DGEO = 85553)
        INTEGER PGSAA_E_SUPPORTID
        PARAMETER (PGSAA_E_SUPPORTID = 85554)
        INTEGER PGSAA_E_MINMAX
        PARAMETER (PGSAA_E_MINMAX = 85555)
        INTEGER PGSAA_E_DATATYPE
        PARAMETER (PGSAA_E_DATATYPE = 85556)
        INTEGER PGSAA_E_UNKNOWN_DATATYPE
        PARAMETER (PGSAA_E_UNKNOWN_DATATYPE = 85557)
        INTEGER PGSAA_W_MISSING_POINTS
        PARAMETER (PGSAA_W_MISSING_POINTS = 85046)
