        INTEGER PGSEPH_E_SIMULATOR_ERROR
        PARAMETER (PGSEPH_E_SIMULATOR_ERROR = 44544)
        INTEGER PGSEPH_W_BAD_EPHEM_VALUE
        PARAMETER (PGSEPH_W_BAD_EPHEM_VALUE = 44033)
        INTEGER PGSEPH_E_BAD_ARRAY_SIZE
        PARAMETER (PGSEPH_E_BAD_ARRAY_SIZE = 44546)
        INTEGER PGSEPH_E_NO_SC_EPHEM_FILE
        PARAMETER (PGSEPH_E_NO_SC_EPHEM_FILE = 44547)
        INTEGER PGSEPH_E_BAD_EPHEM_FILE_HDR
        PARAMETER (PGSEPH_E_BAD_EPHEM_FILE_HDR = 44548)
        INTEGER PGSEPH_E_BAD_TIME_ORDER
        PARAMETER (PGSEPH_E_BAD_TIME_ORDER = 44549)
        INTEGER PGSEPH_E_NO_DATA_REQUESTED
        PARAMETER (PGSEPH_E_NO_DATA_REQUESTED = 44550)
        INTEGER PGSEPH_M_SHORT_ARRAY
        PARAMETER (PGSEPH_M_SHORT_ARRAY = 42503)
        INTEGER PGSEPH_W_CORRUPT_METADATA
        PARAMETER (PGSEPH_W_CORRUPT_METADATA = 44040)
        INTEGER PGSEPH_W_EPHATT_NUMRECS_DIFFER
        PARAMETER (PGSEPH_W_EPHATT_NUMRECS_DIFFER = 44041)
        INTEGER PGSEPH_W_DBLVALUE_METADATA
        PARAMETER (PGSEPH_W_DBLVALUE_METADATA = 44042)
