        INTEGER PGSTD_M_ASCII_TIME_FMT_B
        PARAMETER (PGSTD_M_ASCII_TIME_FMT_B = 26112)
        INTEGER PGSTD_M_LEAP_SEC_IGNORED
        PARAMETER (PGSTD_M_LEAP_SEC_IGNORED = 26113)
        INTEGER PGSTD_M_TIME_TRUNCATED
        PARAMETER (PGSTD_M_TIME_TRUNCATED = 26114)
        INTEGER PGSTD_W_DATA_FILE_MISSING
        PARAMETER (PGSTD_W_DATA_FILE_MISSING = 27651)
        INTEGER PGSTD_W_JD_OUT_OF_RANGE
        PARAMETER (PGSTD_W_JD_OUT_OF_RANGE = 27652)
        INTEGER PGSTD_W_PRED_LEAPS
        PARAMETER (PGSTD_W_PRED_LEAPS = 27653)
        INTEGER PGSTD_W_BAD_SC_TIME
        PARAMETER (PGSTD_W_BAD_SC_TIME = 27654)
        INTEGER PGSTD_E_BAD_P_FIELD
        PARAMETER (PGSTD_E_BAD_P_FIELD = 28167)
        INTEGER PGSTD_E_DATE_OUT_OF_RANGE
        PARAMETER (PGSTD_E_DATE_OUT_OF_RANGE = 28168)
        INTEGER PGSTD_E_MICSEC_TOO_BIG
        PARAMETER (PGSTD_E_MICSEC_TOO_BIG = 28169)
        INTEGER PGSTD_E_MILSEC_TOO_BIG
        PARAMETER (PGSTD_E_MILSEC_TOO_BIG = 28170)
        INTEGER PGSTD_E_NO_LEAP_SECS
        PARAMETER (PGSTD_E_NO_LEAP_SECS = 28171)
        INTEGER PGSTD_E_SC_TAG_UNKNOWN
        PARAMETER (PGSTD_E_SC_TAG_UNKNOWN = 28172)
        INTEGER PGSTD_E_TIME_FMT_ERROR
        PARAMETER (PGSTD_E_TIME_FMT_ERROR = 28173)
        INTEGER PGSTD_E_TIME_VALUE_ERROR
        PARAMETER (PGSTD_E_TIME_VALUE_ERROR = 28174)
        INTEGER PGSTD_E_UNIX_ERROR
        PARAMETER (PGSTD_E_UNIX_ERROR = 28175)
        INTEGER PGSTD_E_NO_UT1_VALUE
        PARAMETER (PGSTD_E_NO_UT1_VALUE = 28176)
        INTEGER PGSTD_E_BAD_2ND_HDR_FLAG
        PARAMETER (PGSTD_E_BAD_2ND_HDR_FLAG = 28177)
        INTEGER PGSTD_E_BAD_INITIAL_TIME
        PARAMETER (PGSTD_E_BAD_INITIAL_TIME = 28178)
        INTEGER PGSTD_E_BAD_ARRAY_SIZE
        PARAMETER (PGSTD_E_BAD_ARRAY_SIZE = 28179)
        INTEGER PGSTD_E_SECONDS_TOO_BIG
        PARAMETER (PGSTD_E_SECONDS_TOO_BIG = 28180)
        INTEGER PGSTD_E_UTCF_UNINITIALIZED
        PARAMETER (PGSTD_E_UTCF_UNINITIALIZED = 28181)
        INTEGER PGSTD_E_TMDF_UNINITIALIZED
        PARAMETER (PGSTD_E_TMDF_UNINITIALIZED = 28182)
        INTEGER PGSTD_M_HEADER_UPDATED
        PARAMETER (PGSTD_M_HEADER_UPDATED = 26135)
