        INTEGER PGSPC_E_FILE_OPEN_ERROR
        PARAMETER (PGSPC_E_FILE_OPEN_ERROR = 77312)
        INTEGER PGSPC_E_INVALID_MODE
        PARAMETER (PGSPC_E_INVALID_MODE = 77313)
        INTEGER PGSPC_W_NO_FILES_EXIST
        PARAMETER (PGSPC_W_NO_FILES_EXIST = 76802)
        INTEGER PGSPC_W_NO_CONFIG_VALUE
        PARAMETER (PGSPC_W_NO_CONFIG_VALUE = 76803)
        INTEGER PGSPC_E_FILE_READ_ERROR
        PARAMETER (PGSPC_E_FILE_READ_ERROR = 77316)
        INTEGER PGSPC_E_LINE_FORMAT_ERROR
        PARAMETER (PGSPC_E_LINE_FORMAT_ERROR = 77317)
        INTEGER PGSPC_E_ENVIRONMENT_ERROR
        PARAMETER (PGSPC_E_ENVIRONMENT_ERROR = 77318)
        INTEGER PGSPC_W_NO_DATA_PRESENT
        PARAMETER (PGSPC_W_NO_DATA_PRESENT = 76807)
        INTEGER PGSPC_E_DATA_ACCESS_ERROR
        PARAMETER (PGSPC_E_DATA_ACCESS_ERROR = 77320)
        INTEGER PGSPC_W_NO_REFERENCE_FOUND
        PARAMETER (PGSPC_W_NO_REFERENCE_FOUND = 76809)
        INTEGER PGSPC_W_NO_CONFIG_FOR_ID
        PARAMETER (PGSPC_W_NO_CONFIG_FOR_ID = 76810)
        INTEGER PGSPC_W_NO_FILES_FOR_ID
        PARAMETER (PGSPC_W_NO_FILES_FOR_ID = 76811)
        INTEGER PGSPC_W_NO_ATTR_FOR_ID
        PARAMETER (PGSPC_W_NO_ATTR_FOR_ID = 76812)
        INTEGER PGSPC_W_TRUNCATED
        PARAMETER (PGSPC_W_TRUNCATED = 76813)
        INTEGER PGSPC_W_ATTR_TRUNCATED
        PARAMETER (PGSPC_W_ATTR_TRUNCATED = 76814)
        INTEGER PGSPC_W_NO_ATTR_MATCH
        PARAMETER (PGSPC_W_NO_ATTR_MATCH = 76815)
        INTEGER PGSPC_W_INVALID_VERSION
        PARAMETER (PGSPC_W_INVALID_VERSION = 76816)
        INTEGER PGSPC_W_FILE_NOT_ON_DISK
        PARAMETER (PGSPC_W_FILE_NOT_ON_DISK = 76817)
        INTEGER PGSPC_E_NULL_DIVPOINTER_SHM
        PARAMETER (PGSPC_E_NULL_DIVPOINTER_SHM = 77330)
        INTEGER PGSPC_E_INDEX_ERROR_SHM
        PARAMETER (PGSPC_E_INDEX_ERROR_SHM = 77331)
        INTEGER PGSPC_W_NULL_DATA_SHM
        PARAMETER (PGSPC_W_NULL_DATA_SHM = 76820)
        INTEGER PGSPC_E_INV_DIVPOINTER_SHM
        PARAMETER (PGSPC_E_INV_DIVPOINTER_SHM = 77333)
        INTEGER PGSPC_E_EXCEEDED_SHM
        PARAMETER (PGSPC_E_EXCEEDED_SHM = 77334)
        INTEGER PGSPC_E_NO_DEFAULT_LOC
        PARAMETER (PGSPC_E_NO_DEFAULT_LOC = 77335)
        INTEGER PGSPC_E_ENV_NOT_PC
        PARAMETER (PGSPC_E_ENV_NOT_PC = 77336)
        INTEGER PGSPC_C_PGSINFO_PGE_START
        PARAMETER (PGSPC_C_PGSINFO_PGE_START = 78873)
        INTEGER PGSPC_C_PGSINFO_PGE_STOP
        PARAMETER (PGSPC_C_PGSINFO_PGE_STOP = 78874)
        INTEGER PGSPC_C_PGSINFO_TERM_START
        PARAMETER (PGSPC_C_PGSINFO_TERM_START = 78875)
        INTEGER PGSPC_M_TOOLKIT_INIT_PASS
        PARAMETER (PGSPC_M_TOOLKIT_INIT_PASS = 75292)
        INTEGER PGSPC_E_TOOLKIT_INIT_FAIL
        PARAMETER (PGSPC_E_TOOLKIT_INIT_FAIL = 77341)
        INTEGER PGSPC_M_TOOLKIT_TERM_BEGIN
        PARAMETER (PGSPC_M_TOOLKIT_TERM_BEGIN = 75294)
        INTEGER PGSPC_E_PCF_UPDATE_FAILED
        PARAMETER (PGSPC_E_PCF_UPDATE_FAILED = 77343)
        INTEGER PGSPC_W_PCF_CLEANUP_WARN
        PARAMETER (PGSPC_W_PCF_CLEANUP_WARN = 76832)
        INTEGER PGSPC_W_NO_UREF_DATA
        PARAMETER (PGSPC_W_NO_UREF_DATA = 76833)
