        INTEGER PGSMEM_E_MAXSIZE
        PARAMETER (PGSMEM_E_MAXSIZE = 60928)
        INTEGER PGSMEM_E_NO_MEMORY
        PARAMETER (PGSMEM_E_NO_MEMORY = 60929)
        INTEGER PGSMEM_E_ADDR_NOTALLOC
        PARAMETER (PGSMEM_E_ADDR_NOTALLOC = 60930)
        INTEGER PGSMEM_W_MEMORY_USED
        PARAMETER (PGSMEM_W_MEMORY_USED = 60419)
        INTEGER PGSMEM_E_SHM
        PARAMETER (PGSMEM_E_SHM = 60932)
        INTEGER PGSMEM_E_SHM_NOTCREATE
        PARAMETER (PGSMEM_E_SHM_NOTCREATE = 60933)
        INTEGER PGSMEM_E_SHM_MULTICREATE
        PARAMETER (PGSMEM_E_SHM_MULTICREATE = 60934)
        INTEGER PGSMEM_E_SHM_MULTIATTACH
        PARAMETER (PGSMEM_E_SHM_MULTIATTACH = 60935)
        INTEGER PGSMEM_E_SHM_NOTATTACH
        PARAMETER (PGSMEM_E_SHM_NOTATTACH = 60936)
        INTEGER PGSMEM_E_SHM_MAXSIZE
        PARAMETER (PGSMEM_E_SHM_MAXSIZE = 60937)
        INTEGER PGSMEM_E_SHM_ENV
        PARAMETER (PGSMEM_E_SHM_ENV = 60938)
        INTEGER PGSMEM_E_SHM_INVALIDKEY
        PARAMETER (PGSMEM_E_SHM_INVALIDKEY = 60939)
