        INTEGER PGSDEM_E_IMPROPER_TAG
        PARAMETER (PGSDEM_E_IMPROPER_TAG = 118272)
        INTEGER PGSDEM_E_CANNOT_ACCESS_DATA
        PARAMETER (PGSDEM_E_CANNOT_ACCESS_DATA = 118273)
        INTEGER PGSDEM_E_HDFEOS
        PARAMETER (PGSDEM_E_HDFEOS = 118274)
        INTEGER PGSDEM_M_FILLVALUE_INCLUDED
        PARAMETER (PGSDEM_M_FILLVALUE_INCLUDED = 116227)
        INTEGER PGSDEM_M_MULTIPLE_RESOLUTIONS
        PARAMETER (PGSDEM_M_MULTIPLE_RESOLUTIONS = 116228)
        INTEGER PGSDEM_W_HDFEOS
        PARAMETER (PGSDEM_W_HDFEOS = 117765)
