        INTEGER PGSTSF_E_NOT_THREADSAFE
        PARAMETER (PGSTSF_E_NOT_THREADSAFE = 126464)
        INTEGER PGSTSF_E_MUTEXINIT_FAIL
        PARAMETER (PGSTSF_E_MUTEXINIT_FAIL = 126465)
        INTEGER PGSTSF_E_MUTEXLOCK_FAIL
        PARAMETER (PGSTSF_E_MUTEXLOCK_FAIL = 126466)
        INTEGER PGSTSF_W_MUTEXUNLOCK_FAIL
        PARAMETER (PGSTSF_W_MUTEXUNLOCK_FAIL = 125955)
        INTEGER PGSTSF_E_KEYCREATE_FAIL
        PARAMETER (PGSTSF_E_KEYCREATE_FAIL = 126468)
        INTEGER PGSTSF_E_GENERAL_FAILURE
        PARAMETER (PGSTSF_E_GENERAL_FAILURE = 126469)
