        INTEGER PGSIO_E_FILEMAP
        PARAMETER (PGSIO_E_FILEMAP = 11776)
        INTEGER PGSIO_E_GEN_OPEN
        PARAMETER (PGSIO_E_GEN_OPEN = 11777)
        INTEGER PGSIO_E_GEN_OPENMODE
        PARAMETER (PGSIO_E_GEN_OPENMODE = 11778)
        INTEGER PGSIO_E_GEN_FILE_NOEXIST
        PARAMETER (PGSIO_E_GEN_FILE_NOEXIST = 11779)
        INTEGER PGSIO_E_GEN_NO_TEMP_NAME
        PARAMETER (PGSIO_E_GEN_NO_TEMP_NAME = 11780)
        INTEGER PGSIO_E_GEN_REFERENCE_FAILURE
        PARAMETER (PGSIO_E_GEN_REFERENCE_FAILURE = 11781)
        INTEGER PGSIO_E_GEN_CREATE_FAILURE
        PARAMETER (PGSIO_E_GEN_CREATE_FAILURE = 11782)
        INTEGER PGSIO_E_GEN_BAD_FILE_DURATION
        PARAMETER (PGSIO_E_GEN_BAD_FILE_DURATION = 11783)
        INTEGER PGSIO_W_GEN_ACCESS_MODIFIED
        PARAMETER (PGSIO_W_GEN_ACCESS_MODIFIED = 11272)
        INTEGER PGSIO_W_GEN_DURATION_NOMOD
        PARAMETER (PGSIO_W_GEN_DURATION_NOMOD = 11273)
        INTEGER PGSIO_W_GEN_NEW_FILE
        PARAMETER (PGSIO_W_GEN_NEW_FILE = 11274)
        INTEGER PGSIO_E_PARTIAL_NAME
        PARAMETER (PGSIO_E_PARTIAL_NAME = 11787)
        INTEGER PGSIO_E_GEN_NO_FREE_LUN
        PARAMETER (PGSIO_E_GEN_NO_FREE_LUN = 11788)
        INTEGER PGSIO_E_GEN_ILLEGAL_LUN
        PARAMETER (PGSIO_E_GEN_ILLEGAL_LUN = 11789)
        INTEGER PGSIO_W_GEN_UNUSED_LUN
        PARAMETER (PGSIO_W_GEN_UNUSED_LUN = 11278)
        INTEGER PGSIO_W_GEN_OLD_FILE
        PARAMETER (PGSIO_W_GEN_OLD_FILE = 11279)
        INTEGER PGSIO_E_GEN_OPEN_OLD
        PARAMETER (PGSIO_E_GEN_OPEN_OLD = 11792)
        INTEGER PGSIO_E_GEN_OPEN_NEW
        PARAMETER (PGSIO_E_GEN_OPEN_NEW = 11793)
        INTEGER PGSIO_E_GEN_OPEN_UNKNOWN
        PARAMETER (PGSIO_E_GEN_OPEN_UNKNOWN = 11794)
        INTEGER PGSIO_E_GEN_OPEN_RECL
        PARAMETER (PGSIO_E_GEN_OPEN_RECL = 11795)
        INTEGER PGSIO_E_GEN_FILE_NODEL
        PARAMETER (PGSIO_E_GEN_FILE_NODEL = 11796)
        INTEGER PGSIO_W_GEN_FILE_NOT_FOUND
        PARAMETER (PGSIO_W_GEN_FILE_NOT_FOUND = 11285)
        INTEGER PGSIO_E_GEN_CLOSE
        PARAMETER (PGSIO_E_GEN_CLOSE = 11798)
        INTEGER PGSIO_E_GEN_BAD_ENVIRONMENT
        PARAMETER (PGSIO_E_GEN_BAD_ENVIRONMENT = 11799)
        INTEGER PGSIO_E_L0_BAD_BUF_SIZ
        PARAMETER (PGSIO_E_L0_BAD_BUF_SIZ = 11800)
        INTEGER PGSIO_E_L0_BAD_SPACECRAFT_TAG
        PARAMETER (PGSIO_E_L0_BAD_SPACECRAFT_TAG = 11801)
        INTEGER PGSIO_E_L0_FSEEK
        PARAMETER (PGSIO_E_L0_FSEEK = 11802)
        INTEGER PGSIO_E_L0_MANAGE_TABLE
        PARAMETER (PGSIO_E_L0_MANAGE_TABLE = 11803)
        INTEGER PGSIO_E_L0_PHYSICAL_OPEN
        PARAMETER (PGSIO_E_L0_PHYSICAL_OPEN = 11804)
        INTEGER PGSIO_E_L0_UNEXPECTED_EOF
        PARAMETER (PGSIO_E_L0_UNEXPECTED_EOF = 11805)
        INTEGER PGSIO_E_L0_VIRTUAL_DS_NOT_OPEN
        PARAMETER (PGSIO_E_L0_VIRTUAL_DS_NOT_OPEN = 11806)
        INTEGER PGSIO_M_L0_HEADER_CHANGED
        PARAMETER (PGSIO_M_L0_HEADER_CHANGED = 9759)
        INTEGER PGSIO_W_L0_PKT_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_PKT_BUF_TRUNCATE = 11296)
        INTEGER PGSIO_W_L0_PHYSICAL_CLOSE
        PARAMETER (PGSIO_W_L0_PHYSICAL_CLOSE = 11297)
        INTEGER PGSIO_E_L0_INIT_FILE_TABLE
        PARAMETER (PGSIO_E_L0_INIT_FILE_TABLE = 11810)
        INTEGER PGSIO_E_L0_INVALID_FILE_LOGICAL
        PARAMETER (PGSIO_E_L0_INVALID_FILE_LOGICAL = 11811)
        INTEGER PGSIO_E_L0_MAP_VERSIONS
        PARAMETER (PGSIO_E_L0_MAP_VERSIONS = 11812)
        INTEGER PGSIO_E_L0_SEEK_1ST_PACKET
        PARAMETER (PGSIO_E_L0_SEEK_1ST_PACKET = 11813)
        INTEGER PGSIO_W_L0_TIME_NOT_FOUND
        PARAMETER (PGSIO_W_L0_TIME_NOT_FOUND = 11302)
        INTEGER PGSIO_E_L0_SEEK_PACKET
        PARAMETER (PGSIO_E_L0_SEEK_PACKET = 11815)
        INTEGER PGSIO_E_L0_PHYSICAL_NOT_OPEN
        PARAMETER (PGSIO_E_L0_PHYSICAL_NOT_OPEN = 11816)
        INTEGER PGSIO_E_L0_PKT_BUF_OVERFLOW
        PARAMETER (PGSIO_E_L0_PKT_BUF_OVERFLOW = 11817)
        INTEGER PGSIO_W_L0_END_OF_VIRTUAL_DS
        PARAMETER (PGSIO_W_L0_END_OF_VIRTUAL_DS = 11306)
        INTEGER PGSIO_E_L0_NEXT_PHYSICAL
        PARAMETER (PGSIO_E_L0_NEXT_PHYSICAL = 11819)
        INTEGER PGSIO_E_L0_ILLEGAL_COMMAND
        PARAMETER (PGSIO_E_L0_ILLEGAL_COMMAND = 11820)
        INTEGER PGSIO_E_L0_ILLEGAL_PACKET_NUM
        PARAMETER (PGSIO_E_L0_ILLEGAL_PACKET_NUM = 11821)
        INTEGER PGSIO_E_L0_INDEX_OUT_OF_RANGE
        PARAMETER (PGSIO_E_L0_INDEX_OUT_OF_RANGE = 11822)
        INTEGER PGSIO_E_L0_MAX_OPEN_EXCEEDED
        PARAMETER (PGSIO_E_L0_MAX_OPEN_EXCEEDED = 11823)
        INTEGER PGSIO_E_L0_MEM_ALLOC
        PARAMETER (PGSIO_E_L0_MEM_ALLOC = 11824)
        INTEGER PGSIO_E_L0_UNUSED_TABLE_ENTRY
        PARAMETER (PGSIO_E_L0_UNUSED_TABLE_ENTRY = 11825)
        INTEGER PGSIO_E_L0_VERSION_COUNT
        PARAMETER (PGSIO_E_L0_VERSION_COUNT = 11826)
        INTEGER PGSIO_E_L0_VERSION_INFO
        PARAMETER (PGSIO_E_L0_VERSION_INFO = 11827)
        INTEGER PGSIO_E_L0_PACKET_NOT_FOUND
        PARAMETER (PGSIO_E_L0_PACKET_NOT_FOUND = 11828)
        INTEGER PGSIO_E_L0_TIME_CONVERSION
        PARAMETER (PGSIO_E_L0_TIME_CONVERSION = 11829)
        INTEGER PGSIO_E_L0_BAD_FILEINFO
        PARAMETER (PGSIO_E_L0_BAD_FILEINFO = 11830)
        INTEGER PGSIO_E_L0_BAD_NUM_PKTS
        PARAMETER (PGSIO_E_L0_BAD_NUM_PKTS = 11831)
        INTEGER PGSIO_E_L0_BAD_APP_ID
        PARAMETER (PGSIO_E_L0_BAD_APP_ID = 11832)
        INTEGER PGSIO_E_L0_BAD_FIRST_PKTNUM
        PARAMETER (PGSIO_E_L0_BAD_FIRST_PKTNUM = 11833)
        INTEGER PGSIO_E_L0_BAD_DATA_LENGTH
        PARAMETER (PGSIO_E_L0_BAD_DATA_LENGTH = 11834)
        INTEGER PGSIO_E_L0_BAD_NUM_APP_IDS
        PARAMETER (PGSIO_E_L0_BAD_NUM_APP_IDS = 11835)
        INTEGER PGSIO_W_L0_HDR_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_HDR_BUF_TRUNCATE = 11324)
        INTEGER PGSIO_W_L0_FTR_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_FTR_BUF_TRUNCATE = 11325)
        INTEGER PGSIO_W_L0_ALL_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_ALL_BUF_TRUNCATE = 11326)
        INTEGER PGSIO_W_L0_BUFTRUNC_END_DS
        PARAMETER (PGSIO_W_L0_BUFTRUNC_END_DS = 11327)
        INTEGER PGSIO_W_L0_BUFTRUNC_HDR_CHG
        PARAMETER (PGSIO_W_L0_BUFTRUNC_HDR_CHG = 11328)
        INTEGER PGSIO_E_L0_BUFTRUNC_NXTFILE
        PARAMETER (PGSIO_E_L0_BUFTRUNC_NXTFILE = 11841)
        INTEGER PGSIO_W_L0_HDR_TIME_ORDER
        PARAMETER (PGSIO_W_L0_HDR_TIME_ORDER = 11330)
        INTEGER PGSIO_E_L0_BAD_VAR_HDR_SIZE
        PARAMETER (PGSIO_E_L0_BAD_VAR_HDR_SIZE = 11843)
        INTEGER PGSIO_W_L0_BAD_PKT_DATA_SIZE
        PARAMETER (PGSIO_W_L0_BAD_PKT_DATA_SIZE = 11332)
        INTEGER PGSIO_W_L0_BAD_PACKET_COUNT
        PARAMETER (PGSIO_W_L0_BAD_PACKET_COUNT = 11333)
        INTEGER PGSIO_W_L0_BAD_FOOTER_SIZE
        PARAMETER (PGSIO_W_L0_BAD_FOOTER_SIZE = 11334)
        INTEGER PGSIO_W_L0_ZERO_PACKET_COUNT
        PARAMETER (PGSIO_W_L0_ZERO_PACKET_COUNT = 11335)
        INTEGER PGSIO_W_L0_CORRUPT_FILE_HDR
        PARAMETER (PGSIO_W_L0_CORRUPT_FILE_HDR = 11336)
        INTEGER PGSIO_W_L0_BITFLIP_IN_MICSEC
        PARAMETER (PGSIO_W_L0_BITFLIP_IN_MICSEC = 11337)
