        INTEGER PGSCUC_E_CANT_GET_FILE_ID
        PARAMETER (PGSCUC_E_CANT_GET_FILE_ID = 93696)
        INTEGER PGSCUC_E_CANT_OPEN_INPUT_FILE
        PARAMETER (PGSCUC_E_CANT_OPEN_INPUT_FILE = 93697)
        INTEGER PGSCUC_E_AGG_CANT_BE_INSERTED
        PARAMETER (PGSCUC_E_AGG_CANT_BE_INSERTED = 93698)
        INTEGER PGSCUC_E_READLABEL_PARSE_ERROR
        PARAMETER (PGSCUC_E_READLABEL_PARSE_ERROR = 93699)
        INTEGER PGSCUC_E_PARAMETER_INVALID
        PARAMETER (PGSCUC_E_PARAMETER_INVALID = 93700)
        INTEGER PGSCUC_E_FIRST_NODE_NOT_FOUND
        PARAMETER (PGSCUC_E_FIRST_NODE_NOT_FOUND = 93701)
        INTEGER PGSCUC_E__ERROR
        PARAMETER (PGSCUC_E__ERROR = 93702)
        INTEGER PGSCUC_E_COULDNT_INIT_UDUNITS3
        PARAMETER (PGSCUC_E_COULDNT_INIT_UDUNITS3 = 93703)
        INTEGER PGSCUC_E_DONT_KNOW_INP_UNIT
        PARAMETER (PGSCUC_E_DONT_KNOW_INP_UNIT = 93704)
        INTEGER PGSCUC_E_DONT_KNOW_OUTP_UNIT
        PARAMETER (PGSCUC_E_DONT_KNOW_OUTP_UNIT = 93705)
        INTEGER PGSCUC_E_UNITS_ARE_INCOMPATIBLE
        PARAMETER (PGSCUC_E_UNITS_ARE_INCOMPATIBLE = 93706)
        INTEGER PGSCUC_E_A_UNIT_IS_CORRUPTED
        PARAMETER (PGSCUC_E_A_UNIT_IS_CORRUPTED = 91147)
