        INTEGER PGSCBP_E_NO_EPHEMERIS_DATA
        PARAMETER (PGSCBP_E_NO_EPHEMERIS_DATA = 52736)
        INTEGER PGSCBP_E_BAD_ARRAY_SIZE
        PARAMETER (PGSCBP_E_BAD_ARRAY_SIZE = 52737)
        INTEGER PGSCBP_E_BAD_TIME_FORMAT
        PARAMETER (PGSCBP_E_BAD_TIME_FORMAT = 52738)
        INTEGER PGSCBP_E_NO_MEMORY
        PARAMETER (PGSCBP_E_NO_MEMORY = 52739)
        INTEGER PGSCBP_E_BAD_CB_ID
        PARAMETER (PGSCBP_E_BAD_CB_ID = 52740)
        INTEGER PGSCBP_E_TIME_OUT_OF_RANGE
        PARAMETER (PGSCBP_E_TIME_OUT_OF_RANGE = 52741)
        INTEGER PGSCBP_W_EPHEMERIS_ERROR
        PARAMETER (PGSCBP_W_EPHEMERIS_ERROR = 52230)
        INTEGER PGSCBP_E_UNABLE_TO_READ_FILE
        PARAMETER (PGSCBP_E_UNABLE_TO_READ_FILE = 52743)
        INTEGER PGSCBP_E_UNABLE_TO_OPEN_FILE
        PARAMETER (PGSCBP_E_UNABLE_TO_OPEN_FILE = 52744)
        INTEGER PGSCBP_W_NOT_HEADER
        PARAMETER (PGSCBP_W_NOT_HEADER = 52233)
        INTEGER PGSCBP_E_INVALID_NCOEFF
        PARAMETER (PGSCBP_E_INVALID_NCOEFF = 52746)
        INTEGER PGSCBP_E_NO_OVERLAP
        PARAMETER (PGSCBP_E_NO_OVERLAP = 52747)
        INTEGER PGSCBP_W_NO_RECORD_WRITTEN
        PARAMETER (PGSCBP_W_NO_RECORD_WRITTEN = 52236)
        INTEGER PGSCBP_E_INVALID_CB_ID
        PARAMETER (PGSCBP_E_INVALID_CB_ID = 52749)
        INTEGER PGSCBP_E_NO_LIBRATIONS
        PARAMETER (PGSCBP_E_NO_LIBRATIONS = 52750)
        INTEGER PGSCBP_E_TARG_EQUAL_CENTER
        PARAMETER (PGSCBP_E_TARG_EQUAL_CENTER = 52751)
        INTEGER PGSCBP_E_INVALID_FILE_POS
        PARAMETER (PGSCBP_E_INVALID_FILE_POS = 52752)
        INTEGER PGSCBP_E_READ_RECORD_ERROR
        PARAMETER (PGSCBP_E_READ_RECORD_ERROR = 52753)
        INTEGER PGSCBP_E_INVALID_INT_FLAG
        PARAMETER (PGSCBP_E_INVALID_INT_FLAG = 52754)
        INTEGER PGSCBP_E_EPOCH_OUT_OF_SPAN
        PARAMETER (PGSCBP_E_EPOCH_OUT_OF_SPAN = 52755)
        INTEGER PGSCBP_E_NO_NUTATIONS
        PARAMETER (PGSCBP_E_NO_NUTATIONS = 52756)
        INTEGER PGSCBP_E_INVALID_BODY
        PARAMETER (PGSCBP_E_INVALID_BODY = 52757)
        INTEGER PGSCBP_E_BAD_INITIAL_TIME
        PARAMETER (PGSCBP_E_BAD_INITIAL_TIME = 52758)
        INTEGER PGSCBP_W_EARTH_CB_ID
        PARAMETER (PGSCBP_W_EARTH_CB_ID = 52247)
        INTEGER PGSCBP_W_BAD_CB_VECTOR
        PARAMETER (PGSCBP_W_BAD_CB_VECTOR = 52248)
        INTEGER PGSCBP_W_ERROR_IN_BODYINFOV
        PARAMETER (PGSCBP_W_ERROR_IN_BODYINFOV = 52249)
