        INTEGER PGSMET_E_NO_INITIALIZATION
        PARAMETER (PGSMET_E_NO_INITIALIZATION = 110080)
        INTEGER PGSMET_E_AGGREGATE_ERR
        PARAMETER (PGSMET_E_AGGREGATE_ERR = 110081)
        INTEGER PGSMET_E_OPEN_ERR
        PARAMETER (PGSMET_E_OPEN_ERR = 110082)
        INTEGER PGSMET_E_ODL_READ_ERR
        PARAMETER (PGSMET_E_ODL_READ_ERR = 110083)
        INTEGER PGSMET_E_LOAD_ERR
        PARAMETER (PGSMET_E_LOAD_ERR = 110084)
        INTEGER PGSMET_E_DD_UNKNOWN_PARM
        PARAMETER (PGSMET_E_DD_UNKNOWN_PARM = 110085)
        INTEGER PGSMET_E_UNKNOWN_PARM_ATTR
        PARAMETER (PGSMET_E_UNKNOWN_PARM_ATTR = 110086)
        INTEGER PGSMET_E_CORRUPT_MCF
        PARAMETER (PGSMET_E_CORRUPT_MCF = 110087)
        INTEGER PGSMET_E_PARM_NOT_SET
        PARAMETER (PGSMET_E_PARM_NOT_SET = 110088)
        INTEGER PGSMET_W_NO_MAND_PARM
        PARAMETER (PGSMET_W_NO_MAND_PARM = 109577)
        INTEGER PGSMET_E_INV_ODL_TYPE
        PARAMETER (PGSMET_E_INV_ODL_TYPE = 110090)
        INTEGER PGSMET_E_OUTOFRANGE
        PARAMETER (PGSMET_E_OUTOFRANGE = 110091)
        INTEGER PGSMET_E_DD_ERR
        PARAMETER (PGSMET_E_DD_ERR = 110092)
        INTEGER PGSMET_E_MCF_DD_CONFLICT
        PARAMETER (PGSMET_E_MCF_DD_CONFLICT = 110093)
        INTEGER PGSMET_E_LABEL_NOT_FOUND
        PARAMETER (PGSMET_E_LABEL_NOT_FOUND = 110094)
        INTEGER PGSMET_E_CONFIG_VAL_STR_ERR
        PARAMETER (PGSMET_E_CONFIG_VAL_STR_ERR = 110095)
        INTEGER PGSMET_E_CONFIG_CONV_ERR
        PARAMETER (PGSMET_E_CONFIG_CONV_ERR = 110096)
        INTEGER PGSMET_E_INCORRECT_VAL
        PARAMETER (PGSMET_E_INCORRECT_VAL = 110097)
        INTEGER PGSMET_E_NO_INVENT_DATA
        PARAMETER (PGSMET_E_NO_INVENT_DATA = 110098)
        INTEGER PGSMET_E_CONFIG_DATA_ERR
        PARAMETER (PGSMET_E_CONFIG_DATA_ERR = 110099)
        INTEGER PGSMET_E_CONFIRM_ERR
        PARAMETER (PGSMET_E_CONFIRM_ERR = 110100)
        INTEGER PGSMET_E_LOCATION_ERR
        PARAMETER (PGSMET_E_LOCATION_ERR = 110101)
        INTEGER PGSMET_E_NEW_ODL_DATA_ERR
        PARAMETER (PGSMET_E_NEW_ODL_DATA_ERR = 110102)
        INTEGER PGSMET_E_INVALID_DATATYPE
        PARAMETER (PGSMET_E_INVALID_DATATYPE = 110103)
        INTEGER PGSMET_E_CHECK_RANGE_ERR
        PARAMETER (PGSMET_E_CHECK_RANGE_ERR = 110104)
        INTEGER PGSMET_E_PCREAD_ERR
        PARAMETER (PGSMET_E_PCREAD_ERR = 110105)
        INTEGER PGSMET_E_FILETOODL_ERR
        PARAMETER (PGSMET_E_FILETOODL_ERR = 110106)
        INTEGER PGSMET_E_SYS_OPEN_ERR
        PARAMETER (PGSMET_E_SYS_OPEN_ERR = 110107)
        INTEGER PGSMET_E_ODLTOVAL_ERR
        PARAMETER (PGSMET_E_ODLTOVAL_ERR = 110108)
        INTEGER PGSMET_E_SD_START
        PARAMETER (PGSMET_E_SD_START = 110109)
        INTEGER PGSMET_E_SD_FINDATTR
        PARAMETER (PGSMET_E_SD_FINDATTR = 110110)
        INTEGER PGSMET_E_SD_INFO
        PARAMETER (PGSMET_E_SD_INFO = 110111)
        INTEGER PGSMET_E_MALLOC_ERR
        PARAMETER (PGSMET_E_MALLOC_ERR = 110112)
        INTEGER PGSMET_E_SD_READ
        PARAMETER (PGSMET_E_SD_READ = 110113)
        INTEGER PGSMET_W_CLASS_TYPE
        PARAMETER (PGSMET_W_CLASS_TYPE = 109602)
        INTEGER PGSMET_E_SD_SETATTR
        PARAMETER (PGSMET_E_SD_SETATTR = 110115)
        INTEGER PGSMET_E_GROUP_NOT_FOUND
        PARAMETER (PGSMET_E_GROUP_NOT_FOUND = 110116)
        INTEGER PGSMET_E_INCOMP_GROUP
        PARAMETER (PGSMET_E_INCOMP_GROUP = 110117)
        INTEGER PGSMET_E_PCS_OPEN_ERR
        PARAMETER (PGSMET_E_PCS_OPEN_ERR = 110118)
        INTEGER PGSMET_E_ODL_ERROR
        PARAMETER (PGSMET_E_ODL_ERROR = 110119)
        INTEGER PGSMET_W_ODL_WARNING
        PARAMETER (PGSMET_W_ODL_WARNING = 109608)
        INTEGER PGSMET_M_ODL_INFO
        PARAMETER (PGSMET_M_ODL_INFO = 108073)
        INTEGER PGSMET_E_MINMAX_ERR
        PARAMETER (PGSMET_E_MINMAX_ERR = 110122)
        INTEGER PGSMET_E_MCF_TYPE_CONFLICT
        PARAMETER (PGSMET_E_MCF_TYPE_CONFLICT = 110123)
        INTEGER PGSMET_E_MCF_NUMVAL_CONFLICT
        PARAMETER (PGSMET_E_MCF_NUMVAL_CONFLICT = 110124)
        INTEGER PGSMET_E_NESTED_OBJECTS
        PARAMETER (PGSMET_E_NESTED_OBJECTS = 110125)
        INTEGER PGSMET_E_ODL_MEM_ALLOC
        PARAMETER (PGSMET_E_ODL_MEM_ALLOC = 110126)
        INTEGER PGSMET_E_CLASS_PARAMETER
        PARAMETER (PGSMET_E_CLASS_PARAMETER = 110127)
        INTEGER PGSMET_E_METADATA_CHILD
        PARAMETER (PGSMET_E_METADATA_CHILD = 110128)
        INTEGER PGSMET_W_NOT_MULTIPLE
        PARAMETER (PGSMET_W_NOT_MULTIPLE = 109617)
        INTEGER PGSMET_E_NO_DEFINITION
        PARAMETER (PGSMET_E_NO_DEFINITION = 110130)
        INTEGER PGSMET_E_ILLEGAL_NUMVAL
        PARAMETER (PGSMET_E_ILLEGAL_NUMVAL = 110131)
        INTEGER PGSMET_E_ILLEGAL_TYPE
        PARAMETER (PGSMET_E_ILLEGAL_TYPE = 110132)
        INTEGER PGSMET_E_INV_DATATYPE
        PARAMETER (PGSMET_E_INV_DATATYPE = 110133)
        INTEGER PGSMET_E_PARENT_GROUP
        PARAMETER (PGSMET_E_PARENT_GROUP = 110134)
        INTEGER PGSMET_E_MANDATORY_FIELD
        PARAMETER (PGSMET_E_MANDATORY_FIELD = 110135)
        INTEGER PGSMET_E_MANDATORY_DEF
        PARAMETER (PGSMET_E_MANDATORY_DEF = 110136)
        INTEGER PGSMET_E_MANDATORY_VALUE
        PARAMETER (PGSMET_E_MANDATORY_VALUE = 110137)
        INTEGER PGSMET_E_LOC_FIELD
        PARAMETER (PGSMET_E_LOC_FIELD = 110138)
        INTEGER PGSMET_E_LOC_DEF
        PARAMETER (PGSMET_E_LOC_DEF = 110139)
        INTEGER PGSMET_E_LOC_VALUE
        PARAMETER (PGSMET_E_LOC_VALUE = 110140)
        INTEGER PGSMET_E_CONTAINER_LEVELS
        PARAMETER (PGSMET_E_CONTAINER_LEVELS = 110141)
        INTEGER PGSMET_E_DUPLICATE_ERR
        PARAMETER (PGSMET_E_DUPLICATE_ERR = 110142)
        INTEGER PGSMET_E_CLASS
        PARAMETER (PGSMET_E_CLASS = 110143)
        INTEGER PGSMET_E_CLASS_STATEMENTS
        PARAMETER (PGSMET_E_CLASS_STATEMENTS = 110144)
        INTEGER PGSMET_E_INV_NUMVAL
        PARAMETER (PGSMET_E_INV_NUMVAL = 110145)
        INTEGER PGSMET_E_CLASS_DEF
        PARAMETER (PGSMET_E_CLASS_DEF = 110146)
        INTEGER PGSMET_E_CLASS_TYPE
        PARAMETER (PGSMET_E_CLASS_TYPE = 110147)
        INTEGER PGSMET_E_MAND_NOT_SET
        PARAMETER (PGSMET_E_MAND_NOT_SET = 110148)
        INTEGER PGSMET_W_META_NOT_SET
        PARAMETER (PGSMET_W_META_NOT_SET = 109637)
        INTEGER PGSMET_W_METADATA_NOT_SET
        PARAMETER (PGSMET_W_METADATA_NOT_SET = 109638)
        INTEGER PGSMET_E_FGDC_ERR
        PARAMETER (PGSMET_E_FGDC_ERR = 110151)
        INTEGER PGSMET_E_OUTFILE_ERR
        PARAMETER (PGSMET_E_OUTFILE_ERR = 110152)
        INTEGER PGSMET_E_PCF_VALUE_ERR
        PARAMETER (PGSMET_E_PCF_VALUE_ERR = 110153)
        INTEGER PGSMET_E_GRP_ERR
        PARAMETER (PGSMET_E_GRP_ERR = 110154)
        INTEGER PGSMET_E_HDFNOTSET
        PARAMETER (PGSMET_E_HDFNOTSET = 110155)
        INTEGER PGSMET_E_HDFFILENAME_ERR
        PARAMETER (PGSMET_E_HDFFILENAME_ERR = 110156)
        INTEGER PGSMET_E_MET_ASCII_ERR
        PARAMETER (PGSMET_E_MET_ASCII_ERR = 110157)
        INTEGER PGSMET_E_ILLEGAL_HANDLE
        PARAMETER (PGSMET_E_ILLEGAL_HANDLE = 110158)
        INTEGER PGSMET_E_NUMOFMCF_ERR
        PARAMETER (PGSMET_E_NUMOFMCF_ERR = 110159)
        INTEGER PGSMET_E_GRP_NAME_ERR
        PARAMETER (PGSMET_E_GRP_NAME_ERR = 110160)
        INTEGER PGSMET_E_INVALID_LOCATION
        PARAMETER (PGSMET_E_INVALID_LOCATION = 110161)
        INTEGER PGSMET_E_NULL_PARAMETER
        PARAMETER (PGSMET_E_NULL_PARAMETER = 110162)
        INTEGER PGSMET_E_PARAMETER_NOT_SET
        PARAMETER (PGSMET_E_PARAMETER_NOT_SET = 110163)
        INTEGER PGSMET_E_SET_ATTRIBUTE_ERROR
        PARAMETER (PGSMET_E_SET_ATTRIBUTE_ERROR = 110164)
        INTEGER PGSMET_E_SEARCH_FAILED
        PARAMETER (PGSMET_E_SEARCH_FAILED = 110165)
        INTEGER PGSMET_E_GROUP_NOT_FOUND_IN_L7
        PARAMETER (PGSMET_E_GROUP_NOT_FOUND_IN_L7 = 110166)
        INTEGER PGSMET_W_OBJECT_NOT_SET
        PARAMETER (PGSMET_W_OBJECT_NOT_SET = 109655)
        INTEGER PGSMET_E_CONVERT_ERR
        PARAMETER (PGSMET_E_CONVERT_ERR = 110168)
        INTEGER PGSMET_E_TYPE_ERR
        PARAMETER (PGSMET_E_TYPE_ERR = 110169)
        INTEGER PGSMET_E_SET_ERR
        PARAMETER (PGSMET_E_SET_ERR = 110170)
        INTEGER PGSMET_E_ILLEGAL_LENGTH
        PARAMETER (PGSMET_E_ILLEGAL_LENGTH = 110171)
        INTEGER PGSMET_E_ARRAY_ELEMENT_SIZE
        PARAMETER (PGSMET_E_ARRAY_ELEMENT_SIZE = 110172)
        INTEGER PGSMET_E_GETSET_ATTRIBUTE_ERROR
        PARAMETER (PGSMET_E_GETSET_ATTRIBUTE_ERROR = 110173)
        INTEGER PGSMET_M_METADATA_NOT_SET_TK
        PARAMETER (PGSMET_M_METADATA_NOT_SET_TK = 108126)
        INTEGER PGSMET_M_METADATA_NOT_SET_PGE
        PARAMETER (PGSMET_M_METADATA_NOT_SET_PGE = 108127)
        INTEGER PGSMET_E_HDF5_FILE_TYPE_ERROR
        PARAMETER (PGSMET_E_HDF5_FILE_TYPE_ERROR = 110176)
        INTEGER PGSMET_E_SD_END
        PARAMETER (PGSMET_E_SD_END = 110177)
