# HTTP cookie file.
# Generated by Wget on 2021-06-10 17:14:33.
# Edit at your own risk.

.rda.ucar.edu	TRUE	/	TRUE	1638869003	dpass	sBtsKcI829Pg.
.rda.ucar.edu	TRUE	/	FALSE	1638869003	duser	love.sgxl@foxmail.com
